# Generated by Django 2.1.2 on 2018-12-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20181031_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
