# Generated by Django 2.1.2 on 2018-12-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20181204_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
